[workspace]
resolver = "2"
members = [ "day*", "util"]


[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Amr Elghobary <git@amrr.xyz"]

[workspace.dependencies]
util = { path = "util" }
